interface Country {
    name: string;
    aliases: string[];
}

export const countries: Country[] = [
    { name: "Afghanistan", aliases: [] },
    { name: "Albania", aliases: [] },
    { name: "Algeria", aliases: [] },
    { name: "Andorra", aliases: [] },
    { name: "Angola", aliases: [] },
    { name: "Argentina", aliases: [] },
    { name: "Armenia", aliases: [] },
    { name: "Australia", aliases: ["Oz"] },
    { name: "Austria", aliases: [] },
    { name: "Azerbaijan", aliases: [] },
    { name: "Bahamas", aliases: [] },
    { name: "Bahrain", aliases: [] },
    { name: "Bangladesh", aliases: [] },
    { name: "Barbados", aliases: [] },
    { name: "Belarus", aliases: [] },
    { name: "Belgium", aliases: [] },
    { name: "Belize", aliases: [] },
    { name: "Benin", aliases: [] },
    { name: "Bhutan", aliases: [] },
    { name: "Bolivia", aliases: [] },
    { name: "Bosnia and Herzegovina", aliases: ["Bosnia"] },
    { name: "Botswana", aliases: [] },
    { name: "Brazil", aliases: [] },
    { name: "Brunei", aliases: [] },
    { name: "Bulgaria", aliases: [] },
    { name: "Burkina Faso", aliases: [] },
    { name: "Burundi", aliases: [] },
    { name: "Cambodia", aliases: [] },
    { name: "Cameroon", aliases: [] },
    { name: "Canada", aliases: [] },
    { name: "Central African Republic", aliases: ["CAR"] },
    { name: "Chad", aliases: [] },
    { name: "Chile", aliases: [] },
    { name: "China", aliases: ["People's Republic of China", "PRC"] },
    { name: "Colombia", aliases: [] },
    { name: "Congo", aliases: ["Congo-Brazzaville", "Republic of the Congo"] },
    { name: "Costa Rica", aliases: [] },
    { name: "Croatia", aliases: [] },
    { name: "Cuba", aliases: [] },
    { name: "Cyprus", aliases: [] },
    { name: "Czech Republic", aliases: ["Czechia"] },
    { name: "Democratic Republic of the Congo", aliases: ["DRC", "Congo-Kinshasa"] },
    { name: "Denmark", aliases: [] },
    { name: "Djibouti", aliases: [] },
    { name: "Dominican Republic", aliases: [] },
    { name: "Ecuador", aliases: [] },
    { name: "Egypt", aliases: [] },
    { name: "El Salvador", aliases: [] },
    { name: "Equatorial Guinea", aliases: [] },
    { name: "Estonia", aliases: [] },
    { name: "Eswatini", aliases: ["Swaziland"] },
    { name: "Ethiopia", aliases: [] },
    { name: "Fiji", aliases: [] },
    { name: "Finland", aliases: [] },
    { name: "France", aliases: [] },
    { name: "Gabon", aliases: [] },
    { name: "Gambia", aliases: [] },
    { name: "Georgia", aliases: [] },
    { name: "Germany", aliases: ["Deutschland"] },
    { name: "Ghana", aliases: [] },
    { name: "Greece", aliases: [] },
    { name: "Guatemala", aliases: [] },
    { name: "Guinea", aliases: [] },
    { name: "Guyana", aliases: [] },
    { name: "Haiti", aliases: [] },
    { name: "Honduras", aliases: [] },
    { name: "Hungary", aliases: [] },
    { name: "Iceland", aliases: [] },
    { name: "India", aliases: [] },
    { name: "Indonesia", aliases: [] },
    { name: "Iran", aliases: ["Islamic Republic of Iran"] },
    { name: "Iraq", aliases: [] },
    { name: "Ireland", aliases: ["Republic of Ireland"] },
    { name: "Israel", aliases: [] },
    { name: "Italy", aliases: [] },
    { name: "Ivory Coast", aliases: ["Côte d'Ivoire"] },
    { name: "Jamaica", aliases: [] },
    { name: "Japan", aliases: ["Nippon", "Nihon"] },
    { name: "Jordan", aliases: [] },
    { name: "Kazakhstan", aliases: [] },
    { name: "Kenya", aliases: [] },
    { name: "Kuwait", aliases: [] },
    { name: "Kyrgyzstan", aliases: [] },
    { name: "Laos", aliases: [] },
    { name: "Latvia", aliases: [] },
    { name: "Lebanon", aliases: [] },
    { name: "Liberia", aliases: [] },
    { name: "Libya", aliases: [] },
    { name: "Lithuania", aliases: [] },
    { name: "Luxembourg", aliases: [] },
    { name: "Madagascar", aliases: [] },
    { name: "Malawi", aliases: [] },
    { name: "Malaysia", aliases: [] },
    { name: "Maldives", aliases: [] },
    { name: "Mali", aliases: [] },
    { name: "Malta", aliases: [] },
    { name: "Mauritania", aliases: [] },
    { name: "Mexico", aliases: [] },
    { name: "Moldova", aliases: [] },
    { name: "Monaco", aliases: [] },
    { name: "Mongolia", aliases: [] },
    { name: "Montenegro", aliases: [] },
    { name: "Morocco", aliases: [] },
    { name: "Mozambique", aliases: [] },
    { name: "Myanmar", aliases: ["Burma"] },
    { name: "Namibia", aliases: [] },
    { name: "Nepal", aliases: [] },
    { name: "Netherlands", aliases: ["Holland"] },
    { name: "New Zealand", aliases: ["NZ"] },
    { name: "Nicaragua", aliases: [] },
    { name: "Niger", aliases: [] },
    { name: "Nigeria", aliases: [] },
    { name: "North Korea", aliases: ["DPRK"] },
    { name: "North Macedonia", aliases: [] },
    { name: "Norway", aliases: [] },
    { name: "Oman", aliases: [] },
    { name: "Pakistan", aliases: [] },
    { name: "Palestine", aliases: [] },
    { name: "Panama", aliases: [] },
    { name: "Papua New Guinea", aliases: [] },
    { name: "Paraguay", aliases: [] },
    { name: "Peru", aliases: [] },
    { name: "Philippines", aliases: [] },
    { name: "Poland", aliases: [] },
    { name: "Portugal", aliases: [] },
    { name: "Qatar", aliases: [] },
    { name: "Romania", aliases: [] },
    { name: "Russia", aliases: ["Russian Federation"] },
    { name: "Rwanda", aliases: [] },
    { name: "Saudi Arabia", aliases: ["KSA"] },
    { name: "Senegal", aliases: [] },
    { name: "Serbia", aliases: [] },
    { name: "Sierra Leone", aliases: [] },
    { name: "Singapore", aliases: [] },
    { name: "Slovakia", aliases: [] },
    { name: "Slovenia", aliases: [] },
    { name: "Somalia", aliases: [] },
    { name: "South Africa", aliases: ["SA"] },
    { name: "South Korea", aliases: ["Republic of Korea", "ROK"] },
    { name: "South Sudan", aliases: [] },
    { name: "Spain", aliases: [] },
    { name: "Sri Lanka", aliases: [] },
    { name: "Sudan", aliases: [] },
    { name: "Sweden", aliases: [] },
    { name: "Switzerland", aliases: [] },
    { name: "Syria", aliases: [] },
    { name: "Taiwan", aliases: ["Republic of China", "ROC"] },
    { name: "Tanzania", aliases: [] },
    { name: "Thailand", aliases: [] },
    { name: "Togo", aliases: [] },
    { name: "Trinidad and Tobago", aliases: [] },
    { name: "Tunisia", aliases: [] },
    { name: "Turkey", aliases: ["Türkiye"] },
    { name: "Turkmenistan", aliases: [] },
    { name: "Uganda", aliases: [] },
    { name: "Ukraine", aliases: [] },
    { name: "United Arab Emirates", aliases: ["UAE"] },
    { name: "United Kingdom", aliases: ["UK", "U.K.", "Great Britain", "Britain", "England"] },
    { name: "United States", aliases: ["USA", "U.S.A.", "U.S.", "United States of America", "America"] },
    { name: "Uruguay", aliases: [] },
    { name: "Uzbekistan", aliases: [] },
    { name: "Venezuela", aliases: [] },
    { name: "Vietnam", aliases: [] },
    { name: "Yemen", aliases: [] },
    { name: "Zambia", aliases: [] },
    { name: "Zimbabwe", aliases: [] },
];
